[application]

[web.app]

# HTML title tag content
title = "illumos Installer"

[desktop.app]
# Desktop window configuration
title = "illumos Installer"
width = 1024
height = 768
min_width = 800
min_height = 600
resizable = true
maximized = false
decorations = true

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
