#!/usr/bin/env bash
# Generate cloud-init ISO image via Makefile
set -euo pipefail
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR="${SCRIPT_DIR}/../../.."
make -C "$ROOT_DIR" cloud-init-iso
